name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: pdo_mysql
      - name: Install dependencies
        run: composer install
      - name: Set up PostgreSQL
        uses: aiven/setup-postgres@v1
        with:
          pg-version: '13'
          pg-password: ${{ secrets.DB_PASSWORD }}
          pg-database: task_manager
          pg-user: postgres
      - name: Run tests
        run: vendor/bin/phpunit
